@extends('layouts.app') @section('title','Purchase Returns') @section('content')
<div class="space-y-5">
    <div class="flex items-center justify-between mb-6">
        <div>
            <h1 class="font-serif text-3xl text-ink">Purchase Returns</h1>
            <p class="text-sm text-slate-500">Return received goods to a supplier and reverse stock and payable balances.</p>
        </div>
        <a class="btn-teal" href="{{ route('purchases.returns.create') }}">+ New Return / Exchange</a>
    </div>
    
    <form class="card flex flex-wrap gap-3 p-4"><input name="purchase_no" value="{{ request('purchase_no') }}" placeholder="Purchase number" required><button class="btn-primary">Find Purchase</button></form>
@if(request('purchase_no') && !$purchase)<div class="rounded-xl bg-amber-50 p-4 text-amber-800">No purchase matched that number.</div>@endif
@if($purchase)<form method="post" action="{{ route('purchases.returns.store') }}" class="card overflow-hidden">@csrf<input type="hidden" name="purchase_id" value="{{ $purchase->id }}"><div class="flex justify-between border-b p-5"><div><h2 class="font-bold">{{ $purchase->purchase_no }}</h2><p class="text-sm text-slate-500">{{ $purchase->supplier->name }} · {{ $purchase->purchase_date->format('d M Y') }}</p></div><a class="btn-soft" href="{{ route('purchases.show',$purchase) }}">Open Purchase</a></div><div class="overflow-x-auto"><table><thead><tr><th>Product</th><th>Purchased</th><th>Already Returned</th><th>Available</th><th>Return Qty</th><th>Line Total</th></tr></thead><tbody>@foreach($purchase->items as $i) @php $returned=$i->returnItems->sum('quantity');$available=(float)$i->quantity-(float)$returned; @endphp<tr><td>{{ $i->product->name }}</td><td>{{ $i->quantity+0 }} {{ $i->unit->symbol }}</td><td>{{ $returned+0 }}</td><td>{{ $available }}</td><td><input type="number" name="items[{{ $i->id }}]" min="0" max="{{ $available }}" step="0.001" value="0" {{ $available<=0?'disabled':'' }}></td><td>Rs. {{ number_format($i->supplier_line_total,2) }}</td></tr>@endforeach</tbody></table></div><div class="grid gap-4 border-t p-5 md:grid-cols-3"><div><label>Return Date</label><input class="w-full" type="date" name="return_date" value="{{ today()->format('Y-m-d') }}" required></div><div><label>Reason</label><input class="w-full" name="reason" required></div><div><label>Notes</label><input class="w-full" name="notes"></div></div><div class="flex justify-end px-5 pb-5"><button class="btn-teal" onclick="return confirm('Post this purchase return?')">Post Purchase Return</button></div></form>@endif
<div class="card overflow-x-auto"><table><thead><tr><th>Date</th><th>Return</th><th>Purchase</th><th>Supplier</th><th>Amount</th><th>Reason</th></tr></thead><tbody>@forelse($returns as $r)<tr><td>{{ $r->return_date->format('d M Y') }}</td><td>{{ $r->return_no }}</td><td><a class="text-teal" href="{{ route('purchases.show',$r->purchase) }}">{{ $r->purchase->purchase_no }}</a></td><td>{{ $r->supplier->name }}</td><td>Rs. {{ number_format($r->return_total,2) }}</td><td>{{ $r->reason }}</td></tr>@empty<tr><td colspan="6" class="py-10 text-center text-slate-400">No purchase returns.</td></tr>@endforelse</tbody></table></div>{{ $returns->links() }}</div>
@endsection
