<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\ChequeController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ExpenseController;
use App\Http\Controllers\InventoryController;
use App\Http\Controllers\PosController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\PublicInvoiceController;
use App\Http\Controllers\PurchaseController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\ReturnController;
use App\Http\Controllers\SaleController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\TransferController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\StockAdjustmentController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

Route::get('/invoice/view/{token}', PublicInvoiceController::class)->name('invoice.public')->middleware('throttle:60,1');
Route::middleware('guest')->group(function () {
    Route::get('/login', [AuthController::class, 'show'])->name('login');
    Route::post('/login', [AuthController::class, 'login'])->name('login.attempt')->middleware('throttle:5,1');
});

Route::middleware('auth')->group(function () {
    Route::post('/logout', [AuthController::class, 'logout'])->name('logout');
    Route::get('/', DashboardController::class)->name('dashboard')->middleware('permission:dashboard.view');
    Route::get('/profile', [UserController::class, 'profile'])->name('profile');
    Route::put('/profile', [UserController::class, 'updateProfile'])->name('profile.update');
    Route::get('/pos/main', [PosController::class, 'index'])->defaults('type', 'main')->name('pos.main')->middleware('permission:pos.main.access');
    Route::get('/pos/remnant', [PosController::class, 'index'])->defaults('type', 'remnant')->name('pos.remnant')->middleware('permission:pos.remnant.access');
    Route::post('/pos/checkout', [PosController::class, 'checkout'])->name('pos.checkout')->middleware('permission:pos.main.sell|pos.remnant.sell');
    Route::resource('products', ProductController::class)->only(['create', 'store'])->middleware('permission:products.create');
    Route::resource('products', ProductController::class)->only(['index', 'show'])->middleware('permission:products.view');
    Route::resource('products', ProductController::class)->only(['edit', 'update'])->middleware('permission:products.edit');
    Route::resource('products', ProductController::class)->only(['destroy'])->middleware('permission:products.delete');
    Route::post('/products/{product}/toggle-favorite', [ProductController::class, 'toggleFavorite'])->name('products.toggle-favorite');
    Route::get('/purchases/returns', [ReturnController::class, 'purchases'])->name('purchases.returns')->middleware('permission:purchases.return');
    Route::get('/purchases/returns/create', [ReturnController::class, 'createPurchaseReturn'])->name('purchases.returns.create')->middleware('permission:purchases.return');
    Route::get('/api/purchases/supplier/{supplier_id}', [ReturnController::class, 'getSupplierPurchases'])->middleware('permission:purchases.return');
    Route::get('/api/purchases/items/{purchase_id}', [ReturnController::class, 'getPurchaseItems'])->middleware('permission:purchases.return');
    Route::post('/purchases/returns', [ReturnController::class, 'storePurchase'])->name('purchases.returns.store')->middleware('permission:purchases.return');
    Route::get('/sales/returns', [ReturnController::class, 'sales'])->name('sales.returns')->middleware('permission:sales.return');
    Route::post('/sales/returns', [ReturnController::class, 'storeSale'])->name('sales.returns.store')->middleware('permission:sales.return');
    Route::resource('purchases', PurchaseController::class)->only(['create', 'store'])->middleware('permission:purchases.create');
    Route::resource('purchases', PurchaseController::class)->only(['index', 'show'])->middleware('permission:purchases.view');
    Route::resource('purchases', PurchaseController::class)->only(['destroy'])->middleware('permission:purchases.cancel');
    Route::resource('unit-presets', \App\Http\Controllers\UnitPresetController::class)->except(['show'])->middleware('permission:unit_presets.manage');
    Route::resource('sales', SaleController::class)->only(['index', 'show'])->middleware('permission:sales.view');
    Route::get('/sales/{sale}/print', [SaleController::class, 'print'])->name('sales.print')->middleware('permission:sales.view');
    Route::get('/sales/{sale}/pdf', [SaleController::class, 'pdf'])->name('sales.pdf')->middleware('permission:sales.view');
    Route::post('/sales/{sale}/update-customer', [SaleController::class, 'updateCustomer'])->name('sales.update-customer')->middleware('permission:sales.view');
    Route::post('/sales/{sale}/sms', [SaleController::class, 'sms'])->name('sales.sms')->middleware('permission:sales.view');
    Route::resource('customers', CustomerController::class)->only(['index', 'show'])->middleware('permission:customers.view');
    Route::resource('customers', CustomerController::class)->only(['store'])->middleware('permission:customers.create');
    Route::resource('customers', CustomerController::class)->only(['update'])->middleware('permission:customers.edit');
    Route::resource('customers', CustomerController::class)->only(['destroy'])->middleware('permission:customers.deactivate');
    Route::post('/customers/{customer}/toggle', [CustomerController::class, 'toggle'])->name('customers.toggle')->middleware('permission:customers.deactivate');
    Route::post('/customers/{customer}/pay-due', [CustomerController::class, 'payDue'])->name('customers.pay-due')->middleware('permission:customers.pay_due');
    Route::resource('suppliers', SupplierController::class)->only(['index', 'show'])->middleware('permission:suppliers.view');
    Route::resource('suppliers', SupplierController::class)->only(['store'])->middleware('permission:suppliers.create');
    Route::resource('suppliers', SupplierController::class)->only(['update'])->middleware('permission:suppliers.edit');
    Route::resource('suppliers', SupplierController::class)->only(['destroy'])->middleware('permission:suppliers.deactivate');
    Route::post('/suppliers/{supplier}/toggle', [SupplierController::class, 'toggle'])->name('suppliers.toggle')->middleware('permission:suppliers.deactivate');
    Route::post('/suppliers/{supplier}/pay', [SupplierController::class, 'pay'])->name('suppliers.pay')->middleware('permission:suppliers.pay');
    Route::resource('expenses', ExpenseController::class)->only(['index'])->middleware('permission:expenses.view');
    Route::resource('expenses', ExpenseController::class)->only(['store'])->middleware('permission:expenses.create');
    Route::get('/expenses/categories', [ExpenseController::class, 'categories'])->name('expenses.categories')->middleware('permission:expense_categories.manage');
    Route::post('/expenses/categories', [ExpenseController::class, 'storeCategory'])->name('expenses.categories.store')->middleware('permission:expense_categories.manage');
    Route::put('/expenses/categories/{category}', [ExpenseController::class, 'updateCategory'])->name('expenses.categories.update')->middleware('permission:expense_categories.manage');
    Route::delete('/expenses/categories/{category}', [ExpenseController::class, 'destroyCategory'])->name('expenses.categories.destroy')->middleware('permission:expense_categories.manage');
    Route::get('/inventory', [InventoryController::class, 'index'])->name('inventory.index')->middleware('permission:inventory.view');
    Route::get('/inventory/movements', [InventoryController::class, 'movements'])->name('inventory.movements')->middleware('permission:inventory.view');
    Route::get('/inventory/adjustments', [StockAdjustmentController::class, 'index'])->name('inventory.adjustments.index')->middleware('permission:inventory.adjust');
    Route::get('/inventory/adjustments/report', [StockAdjustmentController::class, 'report'])->name('inventory.adjustments.report')->middleware('permission:inventory.adjust');
    Route::get('/inventory/adjustments/create', [StockAdjustmentController::class, 'create'])->name('inventory.adjust')->middleware('permission:inventory.adjust');
    Route::post('/inventory/adjustments', [StockAdjustmentController::class, 'store'])->name('inventory.adjust.store')->middleware('permission:inventory.adjust');
    Route::get('/inventory/adjustments/{adjustment}', [StockAdjustmentController::class, 'show'])->name('inventory.adjustments.show')->middleware('permission:inventory.adjust');
    Route::get('/inventory/adjustments/{adjustment}/edit', [StockAdjustmentController::class, 'edit'])->name('inventory.adjustments.edit')->middleware('permission:inventory.adjust');
    Route::put('/inventory/adjustments/{adjustment}', [StockAdjustmentController::class, 'update'])->name('inventory.adjustments.update')->middleware('permission:inventory.adjust');
    Route::delete('/inventory/adjustments/{adjustment}', [StockAdjustmentController::class, 'destroy'])->name('inventory.adjustments.destroy')->middleware('permission:inventory.adjust');
    Route::get('/remnants', [InventoryController::class, 'remnants'])->name('remnants.index')->middleware('permission:inventory.view');
    Route::get('/remnants/transfer', [InventoryController::class, 'transferForm'])->name('remnants.transfer')->middleware('permission:inventory.remnant_transfer');
    Route::post('/remnants/transfer', [InventoryController::class, 'transfer'])->name('remnants.transfer.store')->middleware('permission:inventory.remnant_transfer');
    Route::get('/transfers', [TransferController::class, 'index'])->name('transfers.index')->middleware('permission:inventory.transfer');
    Route::post('/transfers', [TransferController::class, 'store'])->name('transfers.store')->middleware('permission:inventory.transfer');
    Route::get('/cheques', [ChequeController::class, 'dashboard'])->name('cheques.dashboard')->middleware('permission:cheques.view');
    Route::get('/cheques/all', [ChequeController::class, 'index'])->name('cheques.index')->middleware('permission:cheques.view');
    Route::get('/cheques/received', fn (Request $r) => app(ChequeController::class)->index($r, 'received'))->name('cheques.received')->middleware('permission:cheques.view');
    Route::get('/cheques/issued', fn (Request $r) => app(ChequeController::class)->index($r, 'issued'))->name('cheques.issued')->middleware('permission:cheques.issue');
    Route::get('/cheques/endorsed', fn (Request $r) => app(ChequeController::class)->index($r->merge(['type' => 'endorsed'])))->name('cheques.endorsed')->middleware('permission:cheques.endorse');
    Route::get('/cheques/returned', fn (Request $r) => app(ChequeController::class)->index($r->merge(['status' => 'returned'])))->name('cheques.returned')->middleware('permission:cheques.return');
    Route::get('/cheques/history', [ChequeController::class, 'index'])->name('cheques.history')->middleware('permission:cheques.view');
    Route::get('/cheques/{cheque}', [ChequeController::class, 'show'])->name('cheques.show')->middleware('permission:cheques.view');
    Route::post('/cheques/{cheque}/deposit', [ChequeController::class, 'deposit'])->name('cheques.deposit')->middleware('permission:cheques.pass');
    Route::post('/cheques/{cheque}/pass', [ChequeController::class, 'pass'])->name('cheques.pass')->middleware('permission:cheques.pass');
    Route::post('/cheques/{cheque}/return', [ChequeController::class, 'returnCheque'])->name('cheques.return')->middleware('permission:cheques.return');
    Route::post('/cheques/{cheque}/endorse', [ChequeController::class, 'endorse'])->name('cheques.endorse')->middleware('permission:cheques.endorse');
    Route::post('/cheques/{cheque}/cancel', [ChequeController::class, 'cancel'])->name('cheques.cancel')->middleware('permission:cheques.cancel');
    Route::get('/reports/low-stock', [ReportController::class, 'lowStock'])->name('reports.low-stock')->middleware('permission:reports.low_stock');
    Route::get('/reports/profit-loss', [ReportController::class, 'profit'])->name('reports.profit')->middleware('permission:reports.profit_loss');
    Route::get('/reports/stock-valuation', [ReportController::class, 'valuation'])->name('reports.valuation')->middleware('permission:reports.stock_value');
    Route::get('/reports/dead-stock', [ReportController::class, 'deadStock'])->name('reports.dead')->middleware('permission:reports.dead_stock');
    Route::get('/settings/index', [SettingsController::class, 'show'])->name('settings.index')->middleware('permission:settings.general');
    Route::get('/settings/{section?}', [SettingsController::class, 'show'])->name('settings.show')->middleware('permission:settings.general|settings.business|settings.invoice|settings.pos|settings.product|settings.stock|settings.purchase|settings.sales|settings.customer|settings.supplier|settings.account|settings.payment_methods|settings.sms|settings.report|settings.backup|settings.security|settings.audit');
    Route::put('/settings', [SettingsController::class, 'update'])->name('settings.update')->middleware('permission:settings.general|settings.business|settings.invoice|settings.pos|settings.product|settings.stock|settings.purchase|settings.sales|settings.customer|settings.supplier|settings.account|settings.payment_methods|settings.sms|settings.report|settings.backup|settings.security|settings.audit');

    Route::post('/settings/units', [SettingsController::class, 'unit'])->name('settings.units.store')->middleware('permission:units.manage');
    Route::put('/settings/units/{unit}', [SettingsController::class, 'updateUnit'])->name('settings.units.update')->middleware('permission:units.manage');
    Route::delete('/settings/units/{unit}', [SettingsController::class, 'destroyUnit'])->name('settings.units.destroy')->middleware('permission:units.manage');

    Route::post('/settings/categories', [SettingsController::class, 'category'])->name('settings.categories.store')->middleware('permission:categories.manage');
    Route::put('/settings/categories/{category}', [SettingsController::class, 'updateCategory'])->name('settings.categories.update')->middleware('permission:categories.manage');
    Route::delete('/settings/categories/{category}', [SettingsController::class, 'destroyCategory'])->name('settings.categories.destroy')->middleware('permission:categories.manage');

    Route::post('/settings/brands', [SettingsController::class, 'brand'])->name('settings.brands.store')->middleware('permission:brands.manage');
    Route::put('/settings/brands/{brand}', [SettingsController::class, 'updateBrand'])->name('settings.brands.update')->middleware('permission:brands.manage');
    Route::delete('/settings/brands/{brand}', [SettingsController::class, 'destroyBrand'])->name('settings.brands.destroy')->middleware('permission:brands.manage');

    Route::post('/settings/payment-methods', [SettingsController::class, 'paymentMethod'])->name('settings.payment-methods.store')->middleware('permission:settings.payment_methods');
    Route::put('/settings/payment-methods/{method}', [SettingsController::class, 'updatePaymentMethod'])->name('settings.payment-methods.update')->middleware('permission:settings.payment_methods');
    Route::delete('/settings/payment-methods/{method}', [SettingsController::class, 'destroyPaymentMethod'])->name('settings.payment-methods.destroy')->middleware('permission:settings.payment_methods');

    // Modules not enabled in this installation resolve to their real configuration/report screens.
    Route::resource('users', UserController::class)->only(['create', 'store'])->middleware('permission:users.create');
    Route::resource('users', UserController::class)->only(['index'])->middleware('permission:users.view');
    Route::resource('users', UserController::class)->only(['edit', 'update'])->middleware('permission:users.edit');
    Route::resource('users', UserController::class)->only(['destroy'])->middleware('permission:users.delete');
    Route::resource('roles', RoleController::class)->only(['index'])->middleware('permission:roles.view');
    Route::resource('roles', RoleController::class)->only(['create', 'store'])->middleware('permission:roles.create');
    Route::resource('roles', RoleController::class)->only(['edit', 'update'])->middleware('permission:roles.edit');
    Route::resource('roles', RoleController::class)->only(['destroy'])->middleware('permission:roles.delete');
    Route::get('/categories', [ProductController::class, 'categories'])->name('categories.index')->middleware('permission:categories.manage');
    Route::get('/units', [ProductController::class, 'units'])->name('units.index')->middleware('permission:units.manage');
    Route::get('/brands', [ProductController::class, 'brands'])->name('brands.index')->middleware('permission:brands.manage');
    Route::get('/reports/sales', [ReportController::class, 'sales'])->name('reports.sales')->middleware('permission:reports.sales');
    Route::get('/reports/purchases', [ReportController::class, 'purchases'])->name('reports.purchases')->middleware('permission:reports.purchase');
    Route::get('/reports/stock', [ReportController::class, 'valuation'])->name('reports.stock')->middleware('permission:reports.stock');
    Route::get('/reports/expenses', [ReportController::class, 'expenses'])->name('reports.expenses')->middleware('permission:reports.expenses');
    Route::get('/reports/due-bills', [ReportController::class, 'dueBills'])->name('reports.due-bills')->middleware('permission:reports.customer_due');
    Route::get('/reports/customer-due', [ReportController::class, 'customerDue'])->name('reports.customer-due')->middleware('permission:reports.customer_due');
    Route::get('/reports/supplier-due', [ReportController::class, 'supplierDue'])->name('reports.supplier-due')->middleware('permission:reports.supplier_due');
    Route::get('/reports/cheques', [ChequeController::class, 'index'])->name('reports.cheques')->middleware('permission:reports.cheques');
    Route::get('/reports/daily-closing', [ReportController::class, 'dailyClosing'])->name('reports.daily-closing')->middleware('permission:reports.daily_closing');
    Route::get('/reports/ledger', [ReportController::class, 'ledger'])->name('reports.ledger')->middleware('permission:reports.ledger');
});
