@extends('layouts.app') @section('title','Cheque '.$cheque->cheque_number) @section('content')
<div x-data="{returning:false,endorsing:false,passing:false}" class="space-y-5"><div class="flex flex-wrap justify-between gap-3"><div><a class="text-sm text-slate-500" href="{{ route('cheques.index') }}">← Cheques</a><div class="mt-1 flex items-center gap-3"><h1 class="font-serif text-3xl text-ink">{{ $cheque->cheque_number }}</h1><span class="badge bg-slate-100">{{ ucfirst($cheque->status) }}</span></div><p class="text-sm text-slate-500">{{ ucfirst($cheque->direction) }} · {{ $cheque->bank }} · {{ $cheque->cheque_date->format('d M Y') }}</p></div>@if(in_array($cheque->status,['pending','deposited','endorsed']))<div class="flex flex-wrap gap-2">@if($cheque->direction==='received'&&$cheque->status==='pending')<form method="post" action="{{ route('cheques.deposit',$cheque) }}">@csrf<button class="btn-soft">Mark Deposited</button></form>@endif @if($cheque->direction==='received'&&(float)$cheque->remaining_amount>0)<button class="btn-soft" @click="endorsing=true">Give / Endorse</button>@endif @if(!$cheque->cheque_date->isFuture())
<div x-data="{ passing: false }">
    <button type="button" @click="passing = true" class="btn-teal">PASS / CLEARED</button>
    <template x-teleport="body">
        <div x-show="passing" style="display:none;" class="fixed inset-0 z-[100] flex items-center justify-center bg-slate-900/50 p-4">
            <form method="post" action="{{ route('cheques.pass',$cheque) }}" @click.away="passing = false" class="w-full max-w-sm rounded-2xl bg-white p-6 shadow-xl">
                @csrf
                <h3 class="font-serif text-xl mb-2 text-ink">Pass Cheque</h3>
                <p class="text-sm text-slate-500 mb-5">Select the date this cheque passed. Customer and supplier pending payments will clear exactly once.</p>
                <label class="block text-sm font-medium text-slate-700 mb-1">Pass Date</label>
                <input type="date" name="pass_date" value="{{ today()->format('Y-m-d') }}" class="w-full mb-6 rounded-lg border-slate-300" required>
                <div class="flex justify-end gap-3">
                    <button type="button" @click="passing = false" class="btn-soft">Cancel</button>
                    <button type="submit" class="btn-teal">Confirm Pass</button>
                </div>
            </form>
        </div>
    </template>
</div>
@endif<button id="return" class="btn !bg-red-50 text-red-700" @click="returning=true">RETURN</button>@if($cheque->status==='pending')<form method="post" action="{{ route('cheques.cancel',$cheque) }}" onsubmit="return confirm('Cancel this pending cheque and release its allocations?')">@csrf<button class="btn-soft">Cancel Cheque</button></form>@endif</div>@endif</div>
<div class="grid gap-3 md:grid-cols-3 xl:grid-cols-6">@foreach(['Party'=>$cheque->customer?->name ?? $cheque->supplier?->name,'Amount'=>'Rs. '.number_format($cheque->amount,2),'Endorsed'=>'Rs. '.number_format($cheque->endorsed_amount,2),'Available'=>'Rs. '.number_format($cheque->remaining_amount,2),'Cheque Date'=>$cheque->cheque_date->format('d M Y'),'Status'=>ucfirst($cheque->status)] as $label=>$value)<div class="card p-4"><div class="text-xs uppercase text-slate-400">{{ $label }}</div><div class="mt-2 font-bold">{{ $value }}</div></div>@endforeach</div>
<div class="grid gap-5 xl:grid-cols-2"><div class="card p-5"><h2 class="mb-4 font-serif text-xl">Cheque Details</h2><dl class="grid grid-cols-2 gap-3 text-sm"><dt class="text-slate-400">Bank / Branch</dt><dd>{{ $cheque->bank }} {{ $cheque->branch?'· '.$cheque->branch:'' }}</dd><dt class="text-slate-400">Account Name</dt><dd>{{ $cheque->account_name ?: $cheque->business_bank_account }}</dd><dt class="text-slate-400">Received / Issued</dt><dd>{{ ($cheque->received_date ?? $cheque->issue_date)?->format('d M Y') }}</dd><dt class="text-slate-400">Notes</dt><dd>{{ $cheque->notes ?: '—' }}</dd>@if($cheque->attachment_path)<dt class="text-slate-400">Attachment</dt><dd><a class="text-teal" target="_blank" href="{{ Storage::url($cheque->attachment_path) }}">Open attachment</a></dd>@endif</dl></div><div class="card overflow-x-auto"><div class="p-5"><h2 class="font-serif text-xl">Allocations</h2></div><table><thead><tr><th>Side</th><th>Bill</th><th>Amount</th><th>Status</th></tr></thead><tbody>@foreach($cheque->customerPayments as $p)@foreach($p->allocations as $a)<tr><td>Customer</td><td><a class="text-teal" href="{{ route('sales.show',$a->sale) }}">{{ $a->sale->invoice_no }}</a></td><td>Rs. {{ number_format($a->amount,2) }}</td><td>{{ ucfirst($a->status) }}</td></tr>@endforeach @endforeach @foreach($cheque->supplierPayments as $p)@foreach($p->allocations as $a)<tr><td>Supplier</td><td><a class="text-teal" href="{{ route('purchases.show',$a->purchase) }}">{{ $a->purchase->purchase_no }}</a></td><td>Rs. {{ number_format($a->amount,2) }}</td><td>{{ ucfirst($a->status) }}</td></tr>@endforeach @endforeach</tbody></table></div></div>
<div class="card p-5"><h2 class="mb-5 font-serif text-xl">Cheque History</h2><div class="space-y-4 border-l-2 border-slate-200 pl-5">@foreach($cheque->events as $e)<div class="relative"><span class="absolute -left-[27px] top-1 h-3 w-3 rounded-full bg-teal"></span><div class="text-xs text-slate-400">{{ $e->occurred_at->format('d M Y H:i') }} · {{ $e->user?->name }}</div><div class="font-semibold">{{ $e->description }}</div>@if($e->metadata)<div class="text-xs text-slate-500">{{ collect($e->metadata)->map(fn($v,$k)=>ucfirst($k).': '.$v)->join(' · ') }}</div>@endif</div>@endforeach</div></div>
<div x-show="returning" x-cloak class="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><form method="post" action="{{ route('cheques.return',$cheque) }}" class="card w-full max-w-xl p-6">@csrf<h2 class="font-serif text-2xl">Return Cheque</h2><div class="mt-4 grid gap-4 md:grid-cols-2"><div><label>Return Date</label><input class="w-full" type="date" name="return_date" value="{{ today()->format('Y-m-d') }}" required></div><div><label>Reason</label><input class="w-full" name="return_reason"></div><div><label>Bank Charge</label><input class="w-full" type="number" step=".01" min="0" name="bank_charge" value="0"></div>@if($cheque->customer)<label class="flex items-center gap-2 normal-case"><input type="checkbox" name="charge_customer" value="1"> Add charge to customer due</label>@endif<div class="md:col-span-2"><label>Notes</label><textarea class="w-full" name="notes"></textarea></div></div><div class="mt-5 flex justify-end gap-2"><button type="button" class="btn-soft" @click="returning=false">Cancel</button><button class="btn !bg-red-600 text-white" onclick="return confirm('Return this cheque and restore all linked dues?')">Confirm Return</button></div></form></div>
<div x-show="endorsing" x-cloak class="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><form method="post" action="{{ route('cheques.endorse',$cheque) }}" class="card w-full max-w-xl p-6">@csrf<h2 class="font-serif text-2xl">Give Cheque to Supplier</h2><p class="text-sm text-slate-500">Available Rs. {{ number_format($cheque->remaining_amount,2) }}</p><div class="mt-4 grid gap-4 md:grid-cols-2"><div><label>Supplier</label><select class="w-full" name="supplier_id" required>@foreach($suppliers as $s)<option value="{{ $s->id }}">{{ $s->name }} · Due Rs. {{ number_format(max(0,(float)$s->balance-(float)$s->pending_balance),2) }}</option>@endforeach</select></div><div><label>Amount</label><input class="w-full" type="number" step=".01" max="{{ $cheque->remaining_amount }}" name="amount" required></div><div><label>Transfer Date</label><input class="w-full" type="date" name="transfer_date" value="{{ today()->format('Y-m-d') }}" required></div><input type="hidden" name="allocation_mode" value="automatic"><div><label>Notes</label><input class="w-full" name="notes"></div></div><div class="mt-5 flex justify-end gap-2"><button type="button" class="btn-soft" @click="endorsing=false">Cancel</button><button class="btn-teal">Endorse & Allocate</button></div></form></div></div>
@endsection
