@extends('layouts.app') @section('title','Expenses') @section('content')<div x-data="{open:false}" class="space-y-5"><div class="flex justify-between"><div><h1 class="font-serif text-3xl text-ink">Expenses</h1><p class="text-sm text-slate-500">Operating expenses flow directly into Profit & Loss.</p></div><button class="btn-teal" @click="open=!open">+ Record expense</button></div><form x-show="open" x-cloak method="post" action="{{ route('expenses.store') }}" class="card p-6">@csrf<div class="grid gap-4 md:grid-cols-2 lg:grid-cols-4"><div><label>Date</label><input class="w-full" type="date" name="expense_date" value="{{ now()->toDateString() }}" required></div><div><label>Category</label><select class="w-full" name="expense_category_id" required>@foreach($categories as $c)<option value="{{ $c->id }}">{{ $c->name }}</option>@endforeach</select></div><div><label>Amount</label><input class="w-full" type="number" min="0.01" step="0.01" name="amount" required></div><div><label>Payment method</label><select class="w-full" name="payment_method_id">@foreach($methods as $m)<option value="{{ $m->id }}">{{ $m->name }}</option>@endforeach</select></div><div><label>Store</label><select class="w-full" name="store_id">@foreach($stores as $s)<option value="{{ $s->id }}">{{ $s->name }}</option>@endforeach</select></div><div><label>Reference</label><input class="w-full" name="reference"></div><div class="md:col-span-2"><label>Description</label><input class="w-full" name="description"></div></div><div class="mt-4 flex justify-end"><button class="btn-teal">Save expense</button></div></form>

@component('reports.filters', ['ignore' => ['category_id']])
    <div>
        <label class="block text-sm font-semibold text-slate-700 mb-1">Category</label>
        <select name="category_id" class="rounded-xl border-slate-200 py-2.5 px-3 w-48 bg-white" onchange="document.getElementById('filter-form').submit()">
            <option value="">All Categories</option>
            @foreach($categories as $c)
                <option value="{{ $c->id }}" {{ request('category_id') == $c->id ? 'selected' : '' }}>{{ $c->name }}</option>
            @endforeach
        </select>
    </div>
@endcomponent

<div class="card overflow-x-auto"><table><thead><tr><th>Date</th><th>Category</th><th>Description</th><th>Method</th><th>Reference</th><th>Amount</th></tr></thead><tbody>@forelse($expenses as $e)<tr><td>{{ $e->expense_date->format('d M Y') }}</td><td>{{ $e->category->name }}</td><td>{{ $e->description }}</td><td>{{ $e->paymentMethod->name }}</td><td>{{ $e->reference }}</td><td class="font-semibold">Rs. {{ number_format($e->amount,2) }}</td></tr>@empty<tr><td colspan="6" class="py-12 text-center text-slate-400">No expenses recorded.</td></tr>@endforelse</tbody>@if($expenses->count() > 0)<tfoot><tr><td colspan="5" class="text-right font-bold uppercase text-xs py-4">Total</td><td class="font-bold text-rose-600 py-4">Rs. {{ number_format($totalAmount, 2) }}</td></tr></tfoot>@endif</table></div><div>{{ $expenses->links() }}</div></div>@endsection
