<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title ?? 'Report' }}</title>
    <style>
        body {
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
            color: #333;
            margin: 0;
            padding: 0;
            font-size: 11px; /* Smaller font for reports with many columns */
            line-height: 1.5;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            padding-bottom: 10px;
            border-bottom: 2px solid #ef4444; /* Red brand color */
        }
        .company-name {
            font-size: 24px;
            font-weight: bold;
            color: #1e293b;
            margin-bottom: 5px;
        }
        .report-title {
            font-size: 18px;
            font-weight: bold;
            color: #ef4444;
            text-transform: uppercase;
        }
        .report-meta {
            font-size: 12px;
            color: #64748b;
            margin-top: 5px;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th {
            background-color: #f1f5f9;
            color: #334155;
            font-size: 10px;
            text-transform: uppercase;
            font-weight: bold;
            text-align: left;
            padding: 8px 10px;
            border: 1px solid #cbd5e1;
        }
        th.right, td.right {
            text-align: right;
        }
        th.center, td.center {
            text-align: center;
        }
        td {
            padding: 8px 10px;
            border: 1px solid #e2e8f0;
            color: #334155;
        }
        tr:nth-child(even) td {
            background-color: #f8fafc;
        }
        
        .totals-row td {
            font-weight: bold;
            background-color: #f1f5f9;
            border-top: 2px solid #94a3b8;
            color: #0f172a;
        }
        
        .footer {
            margin-top: 30px;
            font-size: 10px;
            color: #94a3b8;
            text-align: center;
        }
        .page-number:before {
            content: "Page " counter(page);
        }
        
        /* Utility classes */
        .text-red { color: #ef4444; }
        .text-green { color: #10b981; }
        .font-bold { font-weight: bold; }
        
        {!! $extraCss ?? '' !!}
    </style>
</head>
<body>

    <div class="header">
        <div class="company-name">{{ \App\Models\Store::where('is_default', 1)->first()?->name ?? 'Company Name' }}</div>
        <div class="report-title">{{ $title ?? 'Report' }}</div>
        <div class="report-meta">
            @if(isset($period))
                Period: {{ $period }} <br>
            @endif
            Generated on: {{ now()->format('d M Y, H:i A') }}
        </div>
    </div>

    {!! $content !!}

    <div class="footer">
        Generated by System · <span class="page-number"></span>
    </div>

</body>
</html>
