@extends('layouts.app')
@section('title','Customers')
@section('content')
<div x-data="customerManager" class="space-y-5">
  <div class="flex flex-wrap items-center justify-between gap-3"><div><h1 class="font-serif text-3xl text-ink">Customers</h1><p class="text-sm text-slate-500">Search, monitor purchases and collect outstanding balances.</p></div><button class="btn-teal" @click="add=true">+ Add Customer</button></div>
  <form class="card grid gap-3 p-4 md:grid-cols-6">
    <input name="q" value="{{ request('q') }}" placeholder="Name or phone" class="md:col-span-2">
    <select name="status"><option value="all">All statuses</option><option value="active" @selected(request('status')==='active')>Active</option><option value="inactive" @selected(request('status')==='inactive')>Inactive</option></select>
    <select name="inactive_for"><option value="">Any purchase activity</option><option value="30_days" @selected(request('inactive_for')==='30_days')>No purchase 30 days</option><option value="3_months" @selected(request('inactive_for')==='3_months')>No purchase 3 months</option><option value="6_months" @selected(request('inactive_for')==='6_months')>No purchase 6 months</option><option value="1_year" @selected(request('inactive_for')==='1_year')>No purchase 1 year</option></select>
    <label class="flex items-center gap-2 rounded-xl bg-slate-50 px-3 normal-case"><input type="checkbox" name="due_only" value="1" @checked(request('due_only'))> Due only</label>
    <button class="btn-primary">Apply filters</button>
    <div><label>Last purchase from</label><input type="date" name="from" value="{{ request('from') }}" class="w-full"></div><div><label>Last purchase to</label><input type="date" name="to" value="{{ request('to') }}" class="w-full"></div>
  </form>
  <div class="card overflow-x-auto"><table><thead><tr><th>Customer Name</th><th>Phone</th><th>Total Bills</th><th>Total Purchases</th><th>Total Paid</th><th>Current Due</th><th>Last Purchase</th><th>Status</th><th>Actions</th></tr></thead><tbody>
    @forelse($records as $c) @php $currentDue=max(0,(float)$c->balance-(float)($c->pending_sum??0)); $hasTransactions=$c->sales_count+$c->ledger_count+$c->payments_count>0; $editData=json_encode($c->only(['id','name','mobile','whatsapp','email','address','credit_limit','opening_balance','notes'])); @endphp<tr><td><a href="{{ route('customers.show',$c) }}" class="font-semibold text-teal hover:underline">{{ $c->name }}</a>@if($c->is_walk_in)<span class="badge ml-1 bg-slate-100">Protected</span>@endif</td><td>{{ $c->mobile ?: '—' }}</td><td>{{ $c->sales_count }}</td><td>Rs. {{ number_format($c->sales_total ?? 0,2) }}</td><td>Rs. {{ number_format($c->sales_paid ?? 0,2) }}</td><td class="font-bold {{ $currentDue>0?'text-amber-700':'text-emerald-700' }}">Rs. {{ number_format($currentDue,2) }}</td><td>{{ $c->last_purchase_at ? \Carbon\Carbon::parse($c->last_purchase_at)->format('d M Y') : 'Never' }}</td><td><span class="badge {{ $c->active?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500' }}">{{ $c->active?'Active':'Inactive' }}</span></td><td><div class="flex flex-wrap gap-1"><a class="btn-soft !px-2 !py-1" href="{{ route('customers.show',$c) }}">View</a><button type="button" class="btn-soft !px-2 !py-1" data-customer="{{ $editData }}" @click="openEdit($el)">Edit</button>@if($currentDue>0)<a class="btn !bg-amber-100 !px-2 !py-1 text-amber-800" href="{{ route('customers.show',[$c,'pay'=>1]) }}#pay-due">Pay Due</a>@endif @unless($c->is_walk_in)<form method="post" action="{{ route('customers.destroy',$c) }}" onsubmit="return confirm('{{ $hasTransactions?'This customer has transactions and will be deactivated. Continue?':'Delete this customer?' }}')">@csrf @method('DELETE')<button class="btn !bg-red-50 !px-2 !py-1 text-red-700">{{ $hasTransactions?'Deactivate':'Delete' }}</button></form>@endunless</div></td></tr>
    @empty<tr><td colspan="9" class="py-12 text-center text-slate-400">No customers match these filters.</td></tr>@endforelse
  </tbody></table></div>{{ $records->links() }}

  <div x-show="add" x-cloak class="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><form method="post" action="{{ route('customers.store') }}" @click.outside="add=false" class="card w-full max-w-3xl p-6">@csrf <div class="mb-4 flex justify-between"><h2 class="font-serif text-2xl">Add Customer</h2><button type="button" @click="add=false">✕</button></div>@include('customers.partials.form')<div class="mt-5 flex justify-end"><button class="btn-teal">Save Customer</button></div></form></div>
  <div x-show="editOpen" x-cloak class="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><form method="post" :action="'/customers/'+edit.id" @click.outside="editOpen=false" class="card w-full max-w-3xl p-6">@csrf @method('PUT')<div class="mb-4 flex justify-between"><h2 class="font-serif text-2xl">Edit Customer</h2><button type="button" @click="editOpen=false">✕</button></div>@include('customers.partials.form',['editing'=>true])<div class="mt-5 flex justify-end"><button class="btn-teal">Update Customer</button></div></form></div>
</div>
@endsection
