@extends('layouts.app')
@section('title',$customer->name)
@section('content')
@php $methodCodes=$methods->pluck('code','id'); @endphp
<div x-data='{pay:{{ request('pay')?'true':'false' }},method:"",mode:"automatic",codes:@json($methodCodes)}' class="space-y-5">
  <div class="flex flex-wrap items-center justify-between gap-3"><div><a href="{{ route('customers.index') }}" class="text-sm text-slate-500">← Customers</a><h1 class="mt-1 font-serif text-3xl text-ink">{{ $customer->name }}</h1><p class="text-sm text-slate-500">{{ $customer->mobile ?: 'No phone' }} · {{ $customer->active?'Active':'Inactive' }}</p></div><div class="flex gap-2">@if($stats['due']>0)<button id="pay-due" class="btn-teal" @click="pay=true">Pay Due</button>@endif<form method="post" action="{{ route('customers.toggle',$customer) }}">@csrf<button class="btn-soft">{{ $customer->active?'Deactivate':'Activate' }}</button></form></div></div>
  <div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">@foreach(['Total Bills'=>'bills','Total Purchases'=>'purchases','Total Paid'=>'paid','Pending Payments'=>'pending','Total Due'=>'due','Returns'=>'returns'] as $label=>$key)<div class="card p-4"><div class="text-xs uppercase text-slate-400">{{ $label }}</div><div class="mt-2 text-xl font-bold {{ $key==='due'&&$stats[$key]>0?'text-amber-700':'' }}">{{ $key==='bills'?$stats[$key]:'Rs. '.number_format($stats[$key],2) }}</div></div>@endforeach</div>
  <div class="card p-2"><div class="flex flex-wrap gap-1">@foreach(['all'=>'All Transactions','bills'=>'Bills','payments'=>'Payments','due'=>'Due','cheques'=>'Cheques','returns'=>'Returns','sms'=>'SMS History'] as $key=>$label)<a href="{{ route('customers.show',[$customer,'tab'=>$key]) }}" class="btn {{ $tab===$key?'bg-ink text-white':'bg-slate-50 text-slate-600' }}">{{ $label }}</a>@endforeach</div></div>
  <div class="card overflow-x-auto">
  @if($tab==='all')<table><thead><tr><th>Date</th><th>Type</th><th>Reference</th><th>Debit</th><th>Credit</th><th>Pending</th><th>Balance</th><th>Status</th></tr></thead><tbody>@forelse($rows as $row)<tr><td>{{ $row->occurred_at->format('d M Y H:i') }}</td><td>{{ ucwords(str_replace('_',' ',$row->type)) }}</td><td>@if($row->reference instanceof \App\Models\Sale)<a class="text-teal" href="{{ route('sales.show',$row->reference) }}">{{ $row->reference->invoice_no }}</a>@elseif($row->reference instanceof \App\Models\Cheque)<a class="text-teal" href="{{ route('cheques.show',$row->reference) }}">{{ $row->reference->cheque_number }}</a>@elseif($row->reference instanceof \App\Models\CustomerPayment && $row->reference->cheque_id)<a class="text-teal" href="{{ route('cheques.show',$row->reference->cheque_id) }}">{{ $row->reference->reference }}</a>@else{{ $row->notes ?: '—' }}@endif</td><td>Rs. {{ number_format($row->debit,2) }}</td><td>Rs. {{ number_format($row->credit,2) }}</td><td class="{{ $row->pending>0?'text-amber-700':'' }}">{{ $row->pending?('Rs. '.number_format($row->pending,2)):'—' }}</td><td class="font-bold">Rs. {{ number_format($row->balance_after,2) }}</td><td><span class="badge {{ $row->pending>0?'bg-amber-50 text-amber-700':'bg-slate-100' }}">{{ $row->pending>0?'Pending':'Posted' }}</span></td></tr>@empty<tr><td colspan="8" class="py-10 text-center text-slate-400">No transactions.</td></tr>@endforelse</tbody></table>
  @elseif(in_array($tab,['bills','due']))<table><thead><tr><th>Date</th><th>Invoice</th><th>Total</th><th>Cleared</th><th>Pending</th><th>Due</th><th>Status</th></tr></thead><tbody>@foreach($rows as $sale)<tr><td>{{ $sale->sold_at->format('d M Y') }}</td><td><a class="text-teal" href="{{ route('sales.show',$sale) }}">{{ $sale->invoice_no }}</a></td><td>Rs. {{ number_format($sale->grand_total,2) }}</td><td>Rs. {{ number_format($sale->paid_total,2) }}</td><td>Rs. {{ number_format($sale->pending_total,2) }}</td><td>Rs. {{ number_format($sale->due_total,2) }}</td><td><span class="badge {{ $sale->due_total>0?'bg-amber-50 text-amber-700':($sale->pending_total>0?'bg-blue-50 text-blue-700':'bg-emerald-50 text-emerald-700') }}">{{ $sale->due_total>0?($sale->paid_total>0?'Partially Paid':'Due'):($sale->pending_total>0?'Pending Cheque':'Paid') }}</span></td></tr>@endforeach</tbody></table>
  @elseif($tab==='payments')<table><thead><tr><th>Date</th><th>Method</th><th>Reference</th><th>Amount</th><th>Status</th></tr></thead><tbody>@foreach($rows as $p)<tr><td>{{ $p->payment_date->format('d M Y') }}</td><td>{{ $p->method->name }}</td><td>@if($p->cheque)<a class="text-teal" href="{{ route('cheques.show',$p->cheque) }}">{{ $p->reference }}</a>@else{{ $p->reference ?: '—' }}@endif</td><td>Rs. {{ number_format($p->amount,2) }}</td><td><span class="badge bg-slate-100">{{ ucfirst($p->status) }}</span></td></tr>@endforeach</tbody></table>
  @elseif($tab==='cheques')<table><thead><tr><th>Date</th><th>Cheque</th><th>Bank</th><th>Amount</th><th>Status</th></tr></thead><tbody>@foreach($rows as $c)<tr><td>{{ $c->cheque_date->format('d M Y') }}</td><td><a class="text-teal" href="{{ route('cheques.show',$c) }}">{{ $c->cheque_number }}</a></td><td>{{ $c->bank }}</td><td>Rs. {{ number_format($c->amount,2) }}</td><td>{{ ucfirst($c->status) }}</td></tr>@endforeach</tbody></table>
  @elseif($tab==='returns')<table><thead><tr><th>Date</th><th>Return</th><th>Invoice</th><th>Amount</th><th>Settlement</th></tr></thead><tbody>@foreach($rows as $r)<tr><td>{{ $r->return_date->format('d M Y') }}</td><td>{{ $r->return_no }}</td><td><a class="text-teal" href="{{ route('sales.show',$r->sale) }}">{{ $r->sale->invoice_no }}</a></td><td>Rs. {{ number_format($r->return_total,2) }}</td><td>{{ ucwords(str_replace('_',' ',$r->settlement)) }}</td></tr>@endforeach</tbody></table>
  @else<table><thead><tr><th>Date</th><th>Phone</th><th>Message</th><th>Status</th></tr></thead><tbody>@foreach($rows as $sms)<tr><td>{{ $sms->created_at->format('d M Y H:i') }}</td><td>{{ $sms->phone }}</td><td>{{ $sms->message }}</td><td>{{ ucfirst($sms->status) }}</td></tr>@endforeach</tbody></table>@endif
  </div>{{ $rows->links() }}

  <div x-show="pay" x-cloak class="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-slate-950/50 p-4"><form method="post" enctype="multipart/form-data" action="{{ route('customers.pay-due',$customer) }}" @click.outside="pay=false" class="card my-8 w-full max-w-4xl p-6">@csrf <div class="mb-5 flex justify-between"><div><h2 class="font-serif text-2xl">Pay Due</h2><p class="text-sm text-slate-500">{{ $customer->name }} · Current due Rs. {{ number_format($stats['due'],2) }}</p></div><button type="button" @click="pay=false">✕</button></div>
    <div class="grid gap-4 md:grid-cols-3"><div><label>Payment Amount</label><input class="w-full" type="number" name="amount" step="0.01" min="0.01" max="{{ $stats['due'] }}" value="{{ $stats['due'] }}" required></div><div><label>Payment Date</label><input class="w-full" type="date" name="payment_date" value="{{ today()->format('Y-m-d') }}" required></div><div><label>Payment Method</label><select class="w-full" name="payment_method_id" x-model="method" required><option value="">Select method</option>@foreach($methods as $m)<option value="{{ $m->id }}">{{ $m->name }}</option>@endforeach</select></div><div><label>Reference</label><input class="w-full" name="reference"></div><div class="md:col-span-2"><label>Notes</label><input class="w-full" name="notes"></div></div>
    <div x-show="codes[method]==='cheque'" class="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4"><div class="grid gap-4 md:grid-cols-3"><div><label>Cheque Number *</label><input class="w-full" name="cheque_number"></div><div><label>Bank *</label><input class="w-full" name="bank"></div><div><label>Branch</label><input class="w-full" name="branch"></div><div><label>Account Name</label><input class="w-full" name="account_name"></div><div><label>Cheque Date *</label><input class="w-full" type="date" name="cheque_date"></div><div><label>Attachment</label><input class="w-full" type="file" name="attachment" accept="image/*,.pdf"></div></div><p class="mt-3 text-xs font-semibold text-amber-800">This amount remains pending until the cheque passes.</p></div>
    <div class="mt-5"><label>Allocation</label><div class="flex gap-2"><label class="flex items-center gap-2 normal-case"><input type="radio" name="allocation_mode" value="automatic" x-model="mode"> Oldest invoice first</label><label class="flex items-center gap-2 normal-case"><input type="radio" name="allocation_mode" value="manual" x-model="mode"> Manual allocation</label></div></div>
    <div x-show="mode==='manual'" class="mt-3 overflow-x-auto rounded-xl border"><table><thead><tr><th>Invoice</th><th>Date</th><th>Available Due</th><th>Allocate</th></tr></thead><tbody>@foreach($unpaidSales as $sale)<tr><td>{{ $sale->invoice_no }}</td><td>{{ $sale->sold_at->format('d M Y') }}</td><td>Rs. {{ number_format($sale->due_total,2) }}</td><td><input type="number" min="0" max="{{ $sale->due_total }}" step="0.01" name="allocations[{{ $sale->id }}]" value="0"></td></tr>@endforeach</tbody></table></div>
    <div class="mt-5 flex justify-end gap-2"><button type="button" class="btn-soft" @click="pay=false">Cancel</button><button class="btn-teal" onclick="return confirm('Post and allocate this payment?')">Record Payment</button></div>
  </form></div>
</div>
@endsection
