@extends('layouts.app')
@section('title',$supplier->name)
@section('content')
<div x-data='{pay:{{ request('pay')?'true':'false' }},method:"",mode:"automatic",codes:@json($methods->pluck('code','id'))}' class="space-y-5">
<div class="flex flex-wrap justify-between gap-3"><div><a class="text-sm text-slate-500" href="{{ route('suppliers.index') }}">← Suppliers</a><h1 class="font-serif text-3xl text-ink">{{ $supplier->name }}</h1><p class="text-sm text-slate-500">{{ $supplier->company }} · {{ $supplier->phone }}</p></div><div class="flex gap-2">@if($stats['due']>0)<button class="btn-teal" @click="pay=true">Pay Supplier</button>@endif<form method="post" action="{{ route('suppliers.toggle',$supplier) }}">@csrf<button class="btn-soft">{{ $supplier->active?'Deactivate':'Activate' }}</button></form></div></div>
<div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">@foreach(['Total Purchases'=>'purchases','Total Paid'=>'paid','Pending Cheques'=>'pending','Total Due'=>'due','Purchase Returns'=>'returns'] as $label=>$key)<div class="card p-4"><div class="text-xs uppercase text-slate-400">{{ $label }}</div><div class="mt-2 text-xl font-bold">Rs. {{ number_format($stats[$key],2) }}</div></div>@endforeach</div>
<div class="card p-2"><div class="flex flex-wrap gap-1">@foreach(['all'=>'All Transactions','purchases'=>'Purchases','payments'=>'Payments','cheques'=>'Cheques','returns'=>'Returns','ledger'=>'Ledger'] as $key=>$label)<a class="btn {{ ($tab===$key||($key==='ledger'&&$tab==='all'))?'bg-ink text-white':'bg-slate-50' }}" href="{{ route('suppliers.show',[$supplier,'tab'=>$key]) }}">{{ $label }}</a>@endforeach</div></div>
<div class="card overflow-x-auto">@if(in_array($tab,['all','ledger']))<table><thead><tr><th>Date</th><th>Type</th><th>Reference</th><th>Debit</th><th>Credit</th><th>Pending</th><th>Balance</th></tr></thead><tbody>@foreach($rows as $r)<tr><td>{{ $r->occurred_at->format('d M Y H:i') }}</td><td>{{ ucwords(str_replace('_',' ',$r->type)) }}</td><td>{{ $r->notes ?: '—' }}</td><td>Rs. {{ number_format($r->debit,2) }}</td><td>Rs. {{ number_format($r->credit,2) }}</td><td>{{ $r->pending?('Rs. '.number_format($r->pending,2)):'—' }}</td><td class="font-bold">Rs. {{ number_format($r->balance_after,2) }}</td></tr>@endforeach</tbody></table>@elseif($tab==='purchases')<table><thead><tr><th>Date</th><th>Purchase</th><th>Total</th><th>Cleared</th><th>Pending</th><th>Due</th></tr></thead><tbody>@foreach($rows as $p)<tr><td>{{ $p->purchase_date->format('d M Y') }}</td><td><a class="text-teal" href="{{ route('purchases.show',$p) }}">{{ $p->purchase_no }}</a></td><td>Rs. {{ number_format($p->supplier_total,2) }}</td><td>Rs. {{ number_format($p->paid_total,2) }}</td><td>Rs. {{ number_format($p->pending_total,2) }}</td><td>Rs. {{ number_format($p->due_total,2) }}</td></tr>@endforeach</tbody></table>@elseif($tab==='payments')<table><thead><tr><th>Date</th><th>Method</th><th>Reference</th><th>Amount</th><th>Status</th></tr></thead><tbody>@foreach($rows as $p)<tr><td>{{ $p->payment_date->format('d M Y') }}</td><td>{{ $p->method->name }}</td><td>@if($p->cheque)<a class="text-teal" href="{{ route('cheques.show',$p->cheque) }}">{{ $p->reference }}</a>@else{{ $p->reference }}@endif</td><td>Rs. {{ number_format($p->amount,2) }}</td><td>{{ ucfirst($p->status) }}</td></tr>@endforeach</tbody></table>@elseif($tab==='cheques')<table><thead><tr><th>Date</th><th>Cheque</th><th>Bank</th><th>Amount</th><th>Status</th></tr></thead><tbody>@foreach($rows as $c)<tr><td>{{ $c->cheque_date->format('d M Y') }}</td><td><a class="text-teal" href="{{ route('cheques.show',$c) }}">{{ $c->cheque_number }}</a></td><td>{{ $c->bank }}</td><td>Rs. {{ number_format($c->amount,2) }}</td><td>{{ ucfirst($c->status) }}</td></tr>@endforeach</tbody></table>@else<table><thead><tr><th>Date</th><th>Return</th><th>Purchase</th><th>Amount</th><th>Reason</th></tr></thead><tbody>@foreach($rows as $r)<tr><td>{{ $r->return_date->format('d M Y') }}</td><td>{{ $r->return_no }}</td><td>{{ $r->purchase->purchase_no }}</td><td>Rs. {{ number_format($r->return_total,2) }}</td><td>{{ $r->reason }}</td></tr>@endforeach</tbody></table>@endif</div>{{ $rows->links() }}
<div x-show="pay" x-cloak class="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-slate-950/50 p-4"><form method="post" enctype="multipart/form-data" action="{{ route('suppliers.pay',$supplier) }}" class="card my-8 w-full max-w-4xl p-6" @click.outside="pay=false">@csrf<div class="mb-5 flex justify-between"><div><h2 class="font-serif text-2xl">Pay Supplier</h2><p class="text-sm text-slate-500">Due Rs. {{ number_format($stats['due'],2) }}</p></div><button type="button" @click="pay=false">✕</button></div><div class="grid gap-4 md:grid-cols-3"><div><label>Amount</label><input class="w-full" name="amount" type="number" step=".01" max="{{ $stats['due'] }}" required></div><div><label>Date</label><input class="w-full" name="payment_date" type="date" value="{{ today()->format('Y-m-d') }}" required></div><div><label>Method</label><select class="w-full" name="payment_method_id" x-model="method" required><option value="">Select</option>@foreach($methods as $m)<option value="{{ $m->id }}">{{ $m->name }}</option>@endforeach</select></div><div><label>Reference</label><input class="w-full" name="reference"></div><div class="md:col-span-2"><label>Notes</label><input class="w-full" name="notes"></div></div>
<div x-show="codes[method]==='own_cheque'" class="mt-4 rounded-xl bg-amber-50 p-4"><div class="grid gap-3 md:grid-cols-3"><div><label>Cheque Number</label><input class="w-full" name="cheque_number"></div><div><label>Bank</label><input class="w-full" name="bank"></div><div><label>Business Bank Account</label><input class="w-full" name="business_bank_account"></div><div><label>Cheque Date</label><input class="w-full" name="cheque_date" type="date"></div><div><label>Attachment</label><input class="w-full" name="attachment" type="file"></div></div></div>
<div x-show="codes[method]==='endorsed_cheque'" class="mt-4 rounded-xl bg-blue-50 p-4"><label>Eligible Customer Cheque</label><select class="w-full" name="cheque_id"><option value="">Select pending cheque</option>@foreach($eligibleCheques as $c)<option value="{{ $c->id }}">{{ $c->cheque_number }} · {{ $c->customer?->name }} · Available Rs. {{ number_format($c->remaining_amount,2) }}</option>@endforeach</select></div>
<div class="mt-4 flex gap-4"><label class="flex items-center gap-2 normal-case"><input type="radio" name="allocation_mode" value="automatic" x-model="mode"> Oldest purchase first</label><label class="flex items-center gap-2 normal-case"><input type="radio" name="allocation_mode" value="manual" x-model="mode"> Manual</label></div><div x-show="mode==='manual'" class="mt-3 overflow-x-auto"><table><thead><tr><th>Purchase</th><th>Due</th><th>Allocate</th></tr></thead><tbody>@foreach($unpaidPurchases as $p)<tr><td>{{ $p->purchase_no }}</td><td>Rs. {{ number_format($p->due_total,2) }}</td><td><input type="number" name="allocations[{{ $p->id }}]" step=".01" min="0" max="{{ $p->due_total }}" value="0"></td></tr>@endforeach</tbody></table></div><div class="mt-5 flex justify-end"><button class="btn-teal" onclick="return confirm('Post this supplier payment?')">Record Payment</button></div></form></div>
</div>
@endsection
